# Generated by Django 6.0.5 on 2026-06-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_grade_alter_user_name 2"),
        ("users", "0002_alter_user_grade_alter_user_name"),
    ]

    operations = []
