# Generated by Django 6.0.5 on 2026-06-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260625_1312'),
        ('users', '0003_merge_20260627_1619'),
    ]

    operations = [
    ]
