# Generated by Django 6.0.5 on 2026-05-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(help_text='과목 번호 (학수번호)', max_length=20, unique=True)),
                ('subject', models.CharField(help_text='과목명', max_length=100)),
                ('professor', models.CharField(help_text='담당 교수', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(help_text='시험 종류 (중간/기말 등)', max_length=20)),
                ('test_format', models.CharField(help_text='시험 유형 (객관식/주관식 등)', max_length=50)),
                ('rating', models.PositiveIntegerField(default=3, help_text='난이도 별점 (1~5)')),
                ('title', models.CharField(help_text='후기 제목', max_length=200)),
                ('content', models.TextField(help_text='총평 및 내용')),
                ('views', models.PositiveIntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
                ('course', models.ForeignKey(help_text='대상 과목 선택', on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='TestBack.course')),
                ('likes', models.ManyToManyField(blank=True, help_text='좋아요 누른 유저들', related_name='liked_tests', to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, help_text='스크랩한 유저들', related_name='scrapped_tests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('is_anonymous', models.BooleanField(default=True, help_text='익명 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
                ('user', models.ForeignKey(help_text='댓글 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(help_text='해당 시험 후기글', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TestBack.test')),
            ],
        ),
    ]
