# Generated by Django 6.0.5 on 2026-05-29 05:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(help_text='과목 번호 (학수번호)', max_length=20, unique=True)),
                ('subject', models.CharField(help_text='과목명', max_length=100)),
                ('professor', models.CharField(help_text='담당 교수', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(help_text='본명', max_length=50)),
                ('grade', models.IntegerField(default=1, help_text='학년 (1~4)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(help_text='시험 종류 (중간/기말 등)', max_length=20)),
                ('test_format', models.CharField(help_text='시험 유형 (객관식/주관식 등)', max_length=50)),
                ('rating', models.PositiveIntegerField(default=3, help_text='난이도 별점 (1~5)')),
                ('title', models.CharField(help_text='후기 제목', max_length=200)),
                ('content', models.TextField(help_text='총평 및 내용')),
                ('views', models.PositiveIntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
                ('course', models.ForeignKey(help_text='대상 과목 선택', on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='TestBack.course')),
                ('likes', models.ManyToManyField(blank=True, help_text='좋아요 누른 유저들', related_name='liked_tests', to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, help_text='스크랩한 유저들', related_name='scrapped_tests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
